### ISSUE TITLE
task1

### ISSUE THREAD

**Issue by anton-dimension22** [anton-dimension22/dfsdfsdfsdf#18]
```css
block {
height: 100%;
}
```

![31cf56a8d209308888034da836aacea1](https://github.com/user-attachments/assets/6dd611b4-0883-4840-92e6-e09a5990d8c7)

**Comment by anton-dimension22** [comment]
1.  fsdfsddf
    1.  fgdfgfd
    2.  gfdfgfdg
    3.  fgdfgdfg
2.  dfsdfsdfdsfsfd
3.  fgdfgfd
4. dfsdfsdf

**Comment by anton-dimension22** [comment]
```js
const a = 1;
const b = 2;
console.log('hello')
```

dfsdfsdf

```css
.block {
width: 100px;
}
```
